import { defineStrings } from '../../../i18n/ui';

/** Strings for every figure in chapter 6. */
export const s = defineStrings({
  zh: {
    dim: '维度',
    dimValue: '{n} 维',
    spin: '慢慢转动',
    pause: '停下',
    vertices: '顶点',
    edges: '棱',
    legend: '棱的颜色对应它的方向',
    cubeFigure: 'n 维立方体的 Petrie 投影，n 从 0 到 12',
    cubeLabel: '{n} 维立方体的 Petrie 投影：{v} 个顶点、{e} 条棱，外轮廓是正多边形，棱按方向着色',

    predict: '猜一猜：五维立方体有多少条棱？',
    reveal: '揭晓',
    revealCell: '揭晓五维立方体的棱数',
    answerIs: '答案是 {a}。',
    right: '{a}，猜对了。',
    wrong: '答案是 {a}，你猜的是 {g}。',
    tableCaption: 'n 维立方体的 k 维面的个数',
    moreRows: '揭晓之后，表格会一直延伸到 12 维。',
    k0: '顶点',
    k1: '棱',
    k2: '面',
    k3: '胞',

    ballFigure: '单位球的体积，以及它占外切立方体的比例，n 从 0 到 20',
    volumeTitle: '半径为 1 的球的体积',
    shareTitle: '球占外切立方体的比例',
    nAxis: '维度 n',
    ballReadout: '{n} 维：球的体积 {v}，占立方体 {f}',

    cornersFigure: 'n 维立方体的角与内切球的示意图，n 从 2 到 100',
    cornersLabel: '{n} 维示意图：球的半径为 1，立方体的角离中心 {c}；球的体积有 {f} 在最外层十分之一的薄皮里',
    cornerMeter: '角到中心的距离',
    cornerValue: '{c}（球半径为 1）',
    skinMeter: '外层 10% 薄皮里的体积',
  },
  en: {
    dim: 'Dimension',
    dimValue: '{n} dimensions',
    spin: 'Turn slowly',
    pause: 'Stop',
    vertices: 'vertices',
    edges: 'edges',
    legend: 'Edges are coloured by the direction they run in',
    cubeFigure: 'Petrie projection of the n-cube for n from 0 to 12',
    cubeLabel: 'Petrie projection of the {n}-cube: {v} vertices and {e} edges inside a regular polygon, edges coloured by direction',

    predict: 'Guess first: how many edges does the 5-cube have?',
    reveal: 'Reveal',
    revealCell: 'Reveal the number of edges of the 5-cube',
    answerIs: 'It is {a}.',
    right: '{a}. You got it.',
    wrong: 'It is {a}. You guessed {g}.',
    tableCaption: 'Number of k-dimensional faces of the n-cube',
    moreRows: 'Once you reveal it, the table runs all the way to 12 dimensions.',
    k0: 'vertices',
    k1: 'edges',
    k2: 'squares',
    k3: 'cubes',

    ballFigure: 'Volume of the unit ball, and the share of its surrounding cube it fills, for n from 0 to 20',
    volumeTitle: 'Volume of a ball of radius 1',
    shareTitle: 'Share of the surrounding cube it fills',
    nAxis: 'dimension n',
    ballReadout: 'n = {n}: volume {v}, fills {f} of the cube',

    cornersFigure: 'Sketch of the n-cube’s corners around its inscribed ball, for n from 2 to 100',
    cornersLabel: 'Sketch for n = {n}: the ball has radius 1, the cube’s corners are {c} from the centre, and {f} of the ball’s volume lies in its outer tenth',
    cornerMeter: 'Centre to corner',
    cornerValue: '{c} (ball radius 1)',
    skinMeter: 'Volume in the outer 10%',
  },
});
